apiVersion: v1
kind: pod
metadata:
  name: vproapp
  labels:
    app: vproapp
    project: infinity
spec:
  containers:
    - name: app-container
      image: nginx:latest
      ports:
        - containerPort: 80