apiVersion: apps/v1
kind: Replicaset
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
    template:
      metadata:
        labels:
          tier: frontend
      spec:
        containers:
          - name: php-redis
            image: gcr.io/google_samples/gb_frontend:V3